---
name: "Share With User"
guid: "d5b7527c-3c98-4813-8fe7-ce7b31022c53"
version: "1.0.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Share media with specific users"
description: "A Jellyfin plugin to share media with specific users."
category: "General"
owner: "Mitja Henner"
artifacts:
  - "Jellyfin.Plugin.ShareWithUser.dll"
changelog: >
  Initial release
